#!/usr/bin/env python3

import sys, requests

conf_template = 'https://raw.githubusercontent.com/{}/master/{}'

names = [
  'install.conf.json',
  'install.conf.yaml',
  'install.conf.yml',
  'install.yaml',
  'install.yml',
  'install.json',
  'install.conf',
]

for line in sys.stdin:
  repo = line.strip()
  for name in names:
    conf_url = conf_template.format(repo, name)
    sys.stderr.write("getting: {}\n".format(conf_url))
    r = requests.get(conf_url)
    sys.stderr.write("status code: {}\n".format(r.status_code))
    if r.status_code == 200:
      f = open('configs/{}_{}'.format(repo.replace('/','-'), name), 'w+')
      f.write(r.text)
      f.close()
