- clean: ['~']

- shell:
    - [git submodule update --init --recursive, Installing/updating submodules]

- link:
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.gvimrc: gvimrc
    ~/.config/nvim: vim/
    ~/.config/nvim/init.vim: vimrc
    ~/.ghci: ghci
    ~/.gitconfig: gitconfig
    ~/.mjolnir: mjolnir/
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
    - echo "Run 'vim +PluginInstall +qall' to install vim plugins."
