- clean: ['~']
- link:
    ~/.dotfiles: ''
    ~/.tmux: tmux/
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.oh-my-zsh: oh-my-zsh/
- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - "mkdir -p ~/.vimundo"
    - "mkdir -p ~/temp"
    

