- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
