- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.zshrc: zshrc
    ~/.emacs: emacs
    ~/.emacs.d: emacs.d/

- shell:
  - [emacs -q --script emacs.d/lisp/install-packages.el]
  - [git submodule update --init --recursive, Installing submodules]
