- clean: ['~']

- link:
   ~/.aliases: aliases
   ~/.bashrc: bashrc
   ~/.compton: compton
   ~/.config/i3status/config:
      create: true
      path: i3/status
   ~/.config/jumanji/jumanjirc: jumanjirc
   ~/.conkyrc: conkyrc
   ~/.i3/config:
      create: true
      path: i3/config
   ~/.inputrc: inputrc
   ~/.vim:
      create: true
      path: vim/
   ~/.vimrc: vimrc
   ~/.xinitrc: xinitrc
   ~/.Xresources: Xresources

- shell:
   - [git submodule update, Installing/updating submodules]
   - [xrdb -merge ~/.Xresources, Merging Xresources]
