- clean: ['~']

- link:
    ~/.bash_logout: bash_logout
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.bashrc.d: bashrc.d
    ~/.gitignore: gitignore
    ~/.inputrc: inputrc
    ~/.profile: profile
    ~/.vimrc: vimrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - mkdir -m 700 -p ~/{bin,pkg,src}
