- clean: []
- link:
    ~/.bashrc:
        path: bashrc
        force: true
    ~/.bashrc.d: bashrc.d
    ~/.vimrc:
        path: vimrc
        force: true
    ~/.vim: vim
    ~/.config/openbox:
        path: openbox
        force: true
- shell:
    - [git submodule update --init --recursive, Installing submodules]
