- clean: ['~']

- link:
    ~/.gitconfig: gitconfig
    ~/.vimrc: vimrc
    ~/.vim: vim/
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.inputrc: inputrc
    ~/.tmux.conf: tmux.conf
    ~/.xvimrc: xvimrc
