- clean: ['~']

- link:
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.git-completion.bash: git-completion.bash
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.vimrc: vimrc
    ~/.vim:
        path: vim/
        create: true
    ~/.ssh/config:
        path: ssh_config
        create: true
    ~/.atom/config.cson:
        path: atom/config.cson
        create: true
    ~/.atom/keymap.cson:
        path: atom/keymap.cson
        create: true
    ~/.atom/styles.less:
        path: atom/styles.less
        create: true
    ~/.atom/packages.list:
        path: atom/packages.list
        create: true
    ~/.atom/installAtomPackages:
        path: atom/installAtomPackages
        create: true
    ~/.bash-git-prompt:
        path: bash-git-prompt/
        create: true
    ~/.gnupg/scdaemon.conf:
        path: gnupg/scdaemon.conf
        create: true
    ~/.gnupg/gpg.conf:
        path: gnupg/gpg.conf
        create: true
    ~/.gnupg/gpg-agent.conf:
        path: gnupg/gpg-agent.conf
        create: true
    ~/Library/Preferences/com.googlecode.iterm2.plist:
        path: Library/Preferences/com.googlecode.iterm2.plist
        create: true
#    ~/.vim/colors/solarized.vim:
#        path: solarized/vim-colors-solarized/colors/solarized.vim 
#        create: true
#        force: true
    ~/.bin:
        path: bin/
        create: true
    ~/.config/deluge/hostlist.conf.1.2:
        path: config/deluge/hostlist.conf.1.2
        create: true
    ~/.config/deluge/core.conf:
        path: config/deluge/core.conf
        create: true

- shell:
    - 
        description:    "Installing submodules"
        command:        "git submodule update --init --recursive"
        stdout:         true
        stderr:         true
        stdin:          true
    - 
        description:    "Updating submodules"
        command:        "git submodule update --remote --recursive"
        stdout:         true
        stderr:         true
        stdin:          true
    -
        description:    "Installing Atom packages and updating package list"
        command:        "~/.atom/installAtomPackages"
        stdout:         true
        stderr:         true
        stdin:          true
    -
        description:    "Installing vim plugins"
        command:        "vim +PluginInstall +qall"
        stdout:         true
        stderr:         true
        stdin:          true
