- clean: ['~']

- shell:
  - [git submodule update --init --recursive, Installing/updating submodules]

- link:
    ~/.gitconfig: gitconfig
    ~/.zshrc: zshrc
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.rbenv: rbenv/
    ~/.gemrc: gemrc
    ~/.gitignore: gitignore
    ~/.ctags: ctags
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
- link:
    ~/.rbenv/plugins/ruby-build:
        create: true
        path: ruby-build/

