- clean: 
  - "~"
  - "~/.config/terminator"


- link:
    ~/.config/terminator: 
      create: true
      path: config/terminator/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zshrc.pre-oh-my-zsh: zshrc.pre-oh-my-zsh
    

- shell:
  - "vim +PluginInstall +qall"
