- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.zsh: zsh/
    ~/.oh-my-zsh: oh-my-zsh
    ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting: plugins/zsh-syntax-highlighting

- shell:
  - [git submodule update --init --recursive, Installing submodules]
