- clean: ['~']

- link:
    ~/.gitattributes: .gitattributes
    ~/.gitconfig: .gitconfig
    ~/.gitignore_global: .gitignore_global
    ~/.inputrc: .inputrc
    ~/.tmux.conf: .tmux.conf
    ~/.vimrc: .vimrc
    ~/.zshrc: .zshrc
    ~/bin: bin
    ~/.tmuxinator: .tmuxinator
    ~/.vim-snippets: .vim-snippets

- shell:
  - [git submodule update --init --recursive, Installing submodules]
