- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.oh-my-zsh: oh-my-zsh
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing/updating submodules]
  - [~/dotfiles/vim/bundle/YouCompleteMe/install.sh, Installing YouCompleteMe]
