- clean: ['~']

- link:
    ~/.profile:
        path: profile
        create: false
        relink: false
        force: false
    ~/.bash_profile:
        path: bash_profile
        create: false
        relink: false
        force: false
    ~/.bashrc:
        path: bashrc
        create: false
        relink: false
        force: false
    ~/.gitconfig:
        path: gitconfig
        create: false
        relink: false
        force: false
    ~/.zshrc:
        path: zshrc
        create: false
        relink: false
        force: false


