- clean: []
- link:
    ~/.dotfiles: ''
    ~/.bashrc:
        path: bashrc
        force: true
    ~/.bashrc.d: bashrc.d
    ~/.tmux.conf:
        path: tmux.conf
        force: true
    ~/.tmux.conf.d: tmux.conf.d
    ~/.dircolors-solarized: dircolors-solarized
    ~/bin: bin
    ~/.ssh/config.d: ssh.config.d
- shell: []
