- clean: ['~']

- link:
    ~/.config/nvim: nvim/
    ~/.config/mpv: mpv/
    ~/.config/terminator: terminator/
    ~/.zshrc: zsh/zshrc
    ~/.antigen.zsh: zsh/antigen
    ~/.ycm_extra_conf.py: ycm_extra_conf.py
