- clean: ['~']

- link:
   ~/.dotfiles: ''
   ~/.gitconfig: gitconfig
   ~/.tmux.conf: tmux.conf
   ~/.vim: vim/
   ~/.vimrc: vimrc
   ~/.zshrc: zshrc
   ~/.zsh: zsh/

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - command: ./programs.sh
    stdin: true
    stdout: true
    stderr: true
  - command: vim +PluginInstall +qall
    stdin: true
    stdout: true
    stderr: true
