- clean: ['~']

- link:
    ~/.dotfiles: .
    ~/.vim: .vim/
    ~/.vimrc: .vimrc
    ~/.zshrc: .zshrc
    ./oh-my-zsh/custom:
      force: true
      path: .oh-my-custom-zsh/

- shell:
  - [git submodule update --init --recursive, Installing submodules]
