- clean: ['~']

- link:
    ~/antigen.zsh: antigen.zsh
    ~/.config/terminator:
      create: true
      path: .config/terminator/
    ~/.config/htop:
      create: true
      path: .config/htop/
    ~/.dotfiles: ''
    ~/.i3: .i3/
    ~/.i3status.conf: .i3status.conf
    ~/i3-exit: i3-exit
    ~/.vim: .vim/
    ~/.vimrc: .vimrc
    ~/.ssh: .ssh/
    ~/.zshrc: .zshrc
    ~/.gitconfig: .gitconfig
    ~/git-flow-completion.zsh: git-flow-completion.zsh
    ~/.tmux.conf: .tmux.conf

- shell:
  - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
