- clean: ['~']


- link:
    # ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.config/fish: fish/
    ~/.tmux : tmux/ 
- shell:
    - [git submodule update --init --recursive, Installing submodules]
