- clean: ['~']

- link:
    ~/.gitconfig: gitconfig
    ~/.gvimrc: gvimrc
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
