- clean: ['~/.vim/']
- link:
    ~/.Xresources: Xresources
    ~/.xinitrc: xinitrc
    ~/.vimrc: vimrc
    ~/.vim: vim/
    ~/.bashrc: bashrc
    ~/.jshintrc: jshintrc
    ~/bin: bin/
- shell:
  -
    command: mkdir -p ~/{config,ldocs,lwork,ldownloads,storage,docs,work,downloads,programs,projects,media/{video,photo,audio}}
    stdin: false
    stderr: true
    stdout: true
  -
    command: echo "copy fstab to /etc/fstab"
    stdin: false
    stderr: true
    stdout: false
  -
    command: echo "copy nas:smbcredentials to ~/config/smbcredentials"
    stdin: false
    stderr: true
    stdout: false
