- clean: ['~']

- link:
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.bash_logout: bash_logout
    ~/.bash_aliases: bash_aliases
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vim: vim

