- clean: ['~']

- link:
    ~/.vim: vim/
    ~/.profile: profile
    ~/.bashrc: bashrc
    ~/.bash_logout: bash_logout
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.emacs.d/init.el: emacs.d/init.el
    ~/.zshrc: zshrc
- shell:
  - git update-submodules

