- 
  clean: 
    - "~"

- 
  link: 
    ~/.zshrc: zshrc
    ~/.gitconfig: "gitconfig"
    ~/.gitignore_global: "gitignore_global"
    ~/.vim: vim/
    ~/.vimrc: vimrc

- 
  shell: 
    - 
      - "git submodule update --init --recursive --remote"
      - "Installing/updating submodules"
    -
      - "vim +PluginInstall +qall"
      - "Update vim bundles"