- clean: ['~']
- link:
    ~/.dotfiles: ''
    ~/.bin: bin/
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
- shell:
    - [git submodule update --init --recursive, Installing submodules]

