- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf:
      force: true
      path: .tmux.conf
    ~/.bashrc:
      force: true
      path: .bashrc
    ~/.bash_aliases:
      force: true
      path: .bash_aliases
    ~/.bash_functions:
      force: true
      path: .bash_functions
    ~/.inputrc:
      force: true
      path: .inputrc
    ~/.byobu:
      force: true
      path: .byobu/
    ~/.emacs.d:
      force: true
      path: .emacs.d/
    ~/.profile:
      force: true
      path: .profile
    ~/.gitconfig:
      force: true
      path: .gitconfig

- shell:
  - [git submodule update --init --recursive, Installing submodules]

