- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.npmrc: 'npm/npmrc'
    #~/.ackignore: 'ack/ackignore'
    ~/.ackrc: 'ack/ackrc'
    ~/.agignore: 'ag/agignore'
    ~/.agrc: 'ag/agrc'
    ~/.powerline-shell.py: 'powerline/powerline-shell.py'
    ~/.liquidpromptrc: 'liquidprompt/liquidpromptrc'
    ~/.config/liquidprompt/liquid.theme: 'liquidprompt/liquid.theme'
    ~/.bash_aliases: 'bash/bash_aliases'
    ~/.bash_profile: 'bash/bash_profile'
    ~/.bashrc: 'bash/bashrc'
    ~/.wa: 'fish/wahoo.sh'
    ~/.cmus/solarized.theme: 'cmus/solarized.theme'
    ~/.config/fish/config.fish: 'fish/config.fish'
    ~/.config/fish/completions/git.fish: 'fish/git.fish'
    ~/.ctags: 'ctags/ctags'
    #~/.curlrc: 'curl/curlrc'
    ~/.editrc: 'input/editrc'
    ~/.emacs.d: 'emacs/emacs.d/'
    ~/.emacs: 'emacs/emacs'
    ~/.git-completion.bash: 'git/git-completion.bash'
    ~/.git-completion.zsh: 'git/git-completion.zsh'
    ~/.gitattributes: 'git/gitattributes'
    ~/.gitconfig: 'git/gitconfig'
    ~/.gitignore: 'git/gitignore'
    ~/.gitk: 'git/gitk'
    ~/.tigrc: 'git/tigrc'
    ~/.gnupg/gpg-agent.conf: 'gnupg/gpg-agent.conf'
    ~/.gnupg/gpg.conf: 'gnupg/gpg.conf'
    ~/.grc: 'grc/'
    ~/.hgignore: 'mercurial/hgignore'
    ~/.hgrc: 'mercurial/hgrc'
    ~/.hgchangelog.py: 'mercurial/hgchangelog.py'
    ~/.inputrc: 'input/inputrc'
    ~/.irssi: 'irssi/'
    ~/.twitch-irc.sh: 'shell/twitch-irc.sh'
    ~/.z.sh: 'shell/z.sh'
    ~/.z.fish: 'shell/z.fish'
    ~/.livestreamerrc: 'livestreamer/livestreamerrc'
    ~/.my.cnf: 'mysql/my.cnf'
    ~/.nano/syntax-highlighting: 'nano/syntax-highlighting/'
    ~/.nanorc: 'nano/nanorc'
    ~/.psqlrc: 'postgresql/psqlrc'
    ~/.pylintrc: 'python/pylintrc'
    ~/.pythonrc: 'python/pythonrc'
    ~/.tm_properties: 'ruby/tm_properties'
    ~/.rbenv/default-gems: 'ruby/default-gems'
    ~/.aprc: 'ruby/aprc'
    ~/.caprc: 'ruby/caprc'
    ~/.gemrc: 'ruby/gemrc'
    ~/.irbrc: 'ruby/irbrc'
    ~/.pryrc: 'ruby/pryrc'
    ~/.railsrc: 'ruby/railsrc'
    ~/.rdebugrc: 'ruby/rdebugrc'
    ~/.screenrc: 'screen/screenrc'
    ~/.sqliterc: 'sqlite/sqliterc'
    ~/.ssh/config: 'ssh/config'
    ~/.subversion/config: 'subversion/config'
    ~/.subversion/servers: 'subversion/servers'
    ~/.powerline.fish: 'fish/powerline-setup.fish'
    ~/.powerline.bash: 'bash/powerline.sh'
    ~/.powerline.zsh: 'zsh/powerline.zsh'
    ~/.config/powerline: 'powerline/'
    ~/.tmux.conf: 'tmux/tmux.conf'
    ~/.tmux/powerline.conf: 'tmux/powerline.conf'
    ~/.tmux/powerline-base.conf: 'tmux/powerline-base.conf'
    ~/.tmux/powerline_tmux_1.7_plus.conf: 'tmux/powerline_tmux_1.7_plus.conf'
    ~/.tmux/powerline_tmux_1.8_minus.conf: 'tmux/powerline_tmux_1.8_minus.conf'
    ~/.tmux/powerline_tmux_1.8_plus.conf: 'tmux/powerline_tmux_1.8_plus.conf'
    ~/.tmux/powerline_tmux_1.8.conf: 'tmux/powerline_tmux_1.8.conf'
    ~/.tmux/powerline_tmux_1.9_plus.conf: 'tmux/powerline_tmux_1.9_plus.conf'
    ~/.bash_completion_tmux.sh: 'tmux/bash_completion_tmux.sh'
    ~/.vim: 'vim/'
    ~/.vimperatorrc: 'vimperatorrc'
    ~/.vimrc: 'vim/vimrc'
    ~/.gvimrc: 'vim/gvimrc'
    ~/.wgetrc: 'wget/wgetrc'
    ~/.zsh/completions: 'zsh/completions/'
    ~/.zlogin: 'zsh/zlogin'
    ~/.zlogout: 'zsh/zlogout'
    ~/.zpreztorc: 'zsh/zpreztorc'
    ~/.zprofile: 'zsh/zprofile'
    ~/.zshenv: 'zsh/zshenv'
    ~/.zshrc: 'zsh/zshrc'

- shell:
  - 'if [[ -d ${HOME}/.rbenv ]]; then cd ${HOME}/.rbenv && git pull --depth=1; else git clone https://github.com/sstephenson/rbenv.git ~/.rbenv; fi'
  - 'if [[ -d ${HOME}/.rbenv/plugins/ruby-build ]]; then cd ${HOME}/.rbenv/plugins/ruby-build && git pull --depth=1; else git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build; fi'
  - 'if [[ -d ${HOME}/.rbenv/plugins/ ]]; then cd ${HOME}/.rbenv/plugins/rbenv-default-gems && git pull --depth=1; else git clone https://github.com/sstephenson/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems; fi'
  - 'if [[ -d ${HOME}/.rbenv/plugins/rbenv-vars ]]; then cd ${HOME}/.rbenv/plugins/rbenv-vars && git pull --depth=1; else git clone https://github.com/sstephenson/rbenv-vars.git ~/.rbenv/plugins/rbenv-vars; fi'
  - 'if [[ -d ${HOME}/.rbenv/plugins/rbenv-binstubs ]]; then cd ${HOME}/.rbenv/plugins/rbenv-binstubs && git pull --depth=1; else git clone https://github.com/ianheggie/rbenv-binstubs.git ~/.rbenv/plugins/rbenv-binstubs; fi'
  #- 'if [[ -d ${HOME}/.zprezto ]]; then cd ${HOME}/.zprezto && git pull && git submodule update --init --recursive; else git clone --depth=1 --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"; fi'
  #- 'if [[ -d ${HOME}/.vimperator/plugins ]]; then cd ${HOME}/.vimperator/plugins && git pull --depth=1; else git clone --depth=1 https://github.com/vimpr/vimperator-plugins.git ${HOME}/.vimperator/plugins; fi'
  #- 'if [[ -d ${HOME}/.vimperator/colors ]]; then cd ${HOME}/.vimperator/colors && git pull --depth=1; else git clone --depth=1 https://github.com/vimpr/vimperator-colors.git ${HOME}/.vimperator/colors; fi'
  - 'cd ${HOME} && curl -fLo ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim'
  - git submodule update --init --recursive
  # after linking ~/.gitconfig