- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc

- shell:
  - ["git clone https://github.com/gmarik/Vundle.vim.git vim/bundle/Vundle.vim", Installing Vundle]
  - command: vim +PluginInstall +qall
    stdin: true
    stdout: true
    stderr: true
  - ["git clone https://github.com/chriskempson/base16-shell.git ~/.config/base16-shell", Installing Base16-shell]
