- clean: [
    '~'
]

- link:
    ~/.dotfiles: ''
    ~/.bashrc: bash/runcom.bash
    ~/.bash_profile: bash/profile.bash
    ~/.bash_prompt: bash/prompt.bash
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/ignore_global
    ~/.tmux.conf: tmux/tmux.conf
    ~/.vimrc: vim/runcom.vim
    ~/.vim_runtime: vim/vim_runtime/

- shell:
    - [source fonts/install_fonts.bash, Installing fonts]
    - [git submodule update --init --recursive, Installing submodules]
