- clean: ['~']


- link:
    # Vim Configuration
    ~/.vimrc.after: vim/.vimrc.after
    ~/.vimrc.keys: vim/.vimrc.keys
    ~/.vimrc: vim/.vimrc

    # TMUX Configuration
    ~/.tmux.conf: tmux/.tmux.conf

    # Zsh Configuration
    ~/.zshrc: zsh/.zshrc
    # ZgenCustom Configuration
    ~/.zshrc.zgen: zsh/.zshrc.zgen

    ########################################
    # Local Configuration
    ########################################

    # ~/.zshrc.local: zsh/.zshrc.local
    # ~/.vimrc.local: vim/.vimrc.local
    # ~/.vimrc.keys.local: vim/.vimrc.keys.local

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    # - [tmux source-file ~/.tmux.conf, Reloading TMUX configuration (Run in TMUX only)]
