- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.zshrc: zshrc
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.gitignore: gitignore 
    ~/Wombat.itermcolors: Wombat.itermcolors
    ~/.pylintrc: pylintrc
    ~/Library/Developer/Xcode/UserData/FontAndColorThemes/Wombat.dvtcolortheme: "Wombat-256-for-Xcode/Wombat 256 @ZacHallett.dvtcolortheme"

- shell:
    - [git submodule update --init --recursive, "Installing submodules"]

