- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.gitignore_global: gitignore_global

- shell:
  - [git submodule update --init --recursive, Installing submodules]
