- clean: ['~']
- link:
    ~/.bash_profile: bash/bash_profile
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.gemrc: ruby/gemrc
- shell:
  - [git submodule update --init --recursive, Installing submodules...]
  - [~/.dotfiles/osx.sh, Updating OS X preferences...]
  - [~/.dotfiles/font/init.sh, Installing OS X font...]
