- clean: ['~']
- link:
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc:
      relink: true
      path: vimrc
    ~/.conkyrc:
      relink: true
      path: conkyrc
    ~/.zshrc:
      force: true
      path: zshrc
    ~/.i3:
      force: true
      path: i3
- shell:
  - [git submodule update --init --recursive, Installing submodules]
