---
- clean: ['~']

- link:
    '~/.gitconfig': 'git/dot_gitconfig'
    '~/.tmux.conf': 'tmux/tmux.conf'
    '~/.vimrc': 'vim/vimrc'
    '~/.vim': 'vim/vim'
    '~/.config/fish':
      create: true
      path: fish/

- shell:
    - ["./fonts/install.sh", "installing fonts"]
