- clean: ['~']

- link:
    ~/.bash_it: bash_it/
    ~/.vim: vim/
    ~/.gitconfig: gitconfig

- shell:
    - [git submodule update --init --remote, Installing/updating submodules]
    - [rename 's/$/.bak/' ~/.bashrc]
    - [rm ~/.bashrc]

- link:
    ~/.bash_it/aliases/custom.aliases.bash: bash/aliases/custom.aliases.bash
    ~/.bash_it/completion/custom.completion.bash: bash/completion/custom.completion.bash
    ~/.bash_it/themes/pabloferz: bash/themes/pabloferz/
    ~/.vim/autoload/plug.vim: vim/autoload/vim-plug/plug.vim
    ~/.bashrc: bashrc
    ~/.vimrc: vimrc

- shell:
    # Setting up other configurations (bash-it, vim, etc.)
    -
      command: ./setup
      stdin: true
      stdout: true
      stderr: true
