- clean: ['~']

- link:
    ~/.vimrc: vimrc
    ~/.vim: vim
    ~/.tmux.conf: tmux.conf
    ~/.oh-my-zsh: oh-my-zsh
    ~/.zshrc: zshrc
    ~/.config: config

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [pip install --user powerline-status]
