- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.gitconfig: gitconfig
    ~/.zshrc: zshrc
    ~/.zsh: zsh
    ~/pure.zsh: pure.zsh
    ~/.tmuxinator: tmuxinator/

- shell:
  - git update-submodules
  - Installing/updating submodules
