- clean: ['~']

- shell:
  - [sleep 0, Installing Posquit0's dotfiles]
  - 
    command: [git pull, Updating dotfiles]
    stdout: true
    stderr: true
  - 
    command: [git submodule update --init --recursive --quiet, Installing submodules]
    stdout: true
    stderr: true

- link:
    ~/.tools:
      force: true
      path: tools/
    ~/.bin:
      force: true
      path: bin/
    ~/.alias: .alias
    ~/.bowerrc:
      relink: true
      path: bower/.bowerrc
    ~/.ctags:
      force: true
      path: ctags/.ctags
    ~/.curlrc:
      relink: true
      path: curl/.curlrc
    ~/.gemrc:
      relink: true
      path: ruby/.gemrc
    ~/.rbenv/plugins/ruby-build:
      create: true
      path: tools/ruby-build/
    ~/.gdbinit: gdb/.gdbinit
    ~/.gitconfig:
      force: true
      path: git/.gitconfig
    ~/.gitconfig.local: git/.gitconfig.local
    ~/.irssi: irssi/.irssi
    ~/.npmrc: npm/.npmrc
    ~/.octaverc: octave/.octaverc
    ~/.screenrc: screen/.screenrc
    ~/.tmux: 
      force: true
      path: tmux/.tmux/
    ~/.tmux.conf:
      force: true
      path: tmux/.tmux.conf
    ~/.weechat:
      relink: true
      path: weechat/.weechat/
    ~/.weechat-plugins:
      relink: true
      path: weechat/.weechat-plugins/
    ~/.wgetrc:
      relink: true
      path: wget/.wgetrc
    ~/.vim:
      force: true
      path: vim/.vim/
    ~/.vimrc:
      force: true
      path: vim/.vimrc
    ~/.oh-my-zsh:
      force: true
      path: zsh/.oh-my-zsh/
    ~/.oh-my-zsh-custom:
      force: true
      path: zsh/.oh-my-zsh-custom/
    ~/.zshenv:
      force: true
      path: zsh/.zshenv
    ~/.zshrc:
      force: true
      path: zsh/.zshrc
    ~/.Xmodmap:
      relink: true
      path: X/.Xmodmap

- shell:
  - tmux start-server
  - tmux new-session -d
  - 
    command: [~/.tmux/plugins/tpm/scripts/install_plugins.sh, Installing TMUX plugins]
    stdout: true
    stderr: true
  - tmux kill-server
  - 
    command: [vim +PlugInstall +qall now, Installing Vim plugins]
    stdin: true
    stdout: true
    stderr: true
