- clean: ['~']

- shell:
  - [git submodule update --init --recursive --remote, Installing/updating submodules]

- link:
    ~/.zprezto:
        force: true
        path: prezto/
    ~/.vim:
      force: true
      path: vim/
    ~/.vimrc:
      force: true
      path: loosies/vimrc
    ~/.nvim:
      force: true
      path: vim/
    ~/.nvimrc:
      force: true
      path: loosies/vimrc
    ~/.Xresources:
      force: true
      path: loosies/Xresources
    ~/.config/termite:
      create: true
      force: true
      path: config/termite/
    ~/.config/awesome:
      create: true
      force: true
      path: config/awesome/
    ~/.xbindkeysrc:
      force: true
      path: loosies/xbindkeysrc
