- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.ackrc: ackrc
    ~/.Xresources: Xresources
    ~/.xinitrc: xinitrc
    ~/.xsession: xsession
    ~/.xbindkeysrc: xbindkeysrc
    ~/.dircolors: dircolors
    ~/.mosquitto.conf: mosquitto.conf
    ~/.rvmrc: rvmrc
    ~/.tmux: tmux/
    ~/.mpd: mpd/
    ~/.i3: i3/
    ~/.ncmpcpp: ncmpcpp/
    ~/.fonts: fonts/
    ~/.config/awesome: awesome/
    ~/.config/termite: termite/
    ~/.config/base16-shell: base16-shell/
    ~/.config/btsync: btsync/
    ~/.config/dunst: dunst/
    ~/.gitconfig: gitconfig
    ~/.zprezto: zprezto/
    ~/.zpreztorc: zprezto/runcoms/zpreztorc
    ~/.zlogin: zprezto/runcoms/zlogin
    ~/.zlogout: zprezto/runcoms/zlogout
    ~/.zprofile: zprezto/runcoms/zprofile
    ~/.zshenv: zprezto/runcoms/zshenv
    ~/.zshrc: zprezto/runcoms/zshrc
    ~/.bin: bin/

- shell:
  - ["git submodule update --init --recursive", Installing submodules]
  - ["curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", Installing Vim plugin manager]
