- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.oh-my-zsh: oh-my-zsh
    ~/.tmux.conf: tmux.conf
    ~/.zsh: zsh/
    ~/.zshrc:
        force: true
        path: zshrc
    ~/.gitignore: gitignore
    ~/.gitconfig: gitconfig

- shell:
    - git submodule update --init --recursive
