- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.config/bspwm: bspwm/
    ~/.config/compton.conf: compton.conf
    ~/.config/deadbeef: deadbeef/
    ~/.config/display: display/
    ~/.config/dunst: dunst/
    ~/.config/gtk-2.0: gtk-2.0/
    ~/.config/gtk-3.0: gtk-3.0/
    ~/.config/i3: i3/
    ~/.config/i3blocks: i3blocks/
    ~/.config/i3status: i3status/
    ~/.config/panel: panel/
    ~/.config/plank: plank/
    ~/.config/sxhkd: sxhkd/
    ~/.config/terminator: terminator/
    ~/.config/user-dirs.dirs: user-dirs.dirs
    ~/.config/user-dirs.locale: user-dirs.locale
    ~/bin: bin/
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.gtkrc-2.0: gtkrc-2.0
    ~/.moc: moc/
    ~/.nano: nano/
    ~/.nanorc: nanorc
    ~/.nvidia-settings-rc: nvidia-settings-rc
    ~/.stalonetrayrc: stalonetrayrc
    ~/.xinitrc: xinitrc
    ~/.zlogin: zlogin
    ~/.zshrc: zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
