- clean: ['~', '~/.config']

- link:
    ~/.dotfiles: ''
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

- shell:
    - echo Done
