- clean: [~]

- link:
    ~/.bashrc: bashrc
    ~/.gitconfig: gitconfig
    ~/.gitignore: gitignore
    ~/.tmux.conf: tmux.conf
    ~/.vim: vim/
    ~/.vimrc: vimrc

- shell:
    - [git submodule update --init --recursive, Installing submodules]
