- clean: ['~']
- link:
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux/
    ~/.vim: vim/
    ~/.vimrc: vimrc
    ~/.zsh: zsh/
    ~/.zshrc: zshrc

    ~/.ycm_extra_conf.py: ycm_extra_conf.py
- shell:
    - [git submodule update --init --recursive, Updating submodules]
    - 
      command: ./fonts/install.sh
      stdin: true
      stdout: true
      stderr: true
    - 
      command: vim +PluginInstall +qall
      stdin: true
      stdout: true
      stderr: true
    - 
      command: ~/.vim/bundle/YouCompleteMe/install.sh --clang-completer
      stdin: true
      stdout: true
      stderr: true
    - 
      command: ~/.tmux/install_plugins.sh
      stdin: true
      stdout: true
      stderr: true
