- clean: ['~']

- link:
    ~/.dotfiles: ''
    ~/.tmux.conf: tmux/tmux.conf
    ~/.tmux: tmux/
    ~/.vim: vim/
    ~/.vimrc: vim/vimrc
    ~/.gitconfig: git/gitconfig
    ~/.gitignore: git/gitignore
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv
    ~/.screenrc: screen/screenrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
