---
-
  clean: ['~', '~/.config/fish']
-
  link:
    ~/.dotfiles: ""
    ~/.config/fish:
      create: true
      path: config/fish/
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.atom: atom
-
  shell:
    -
      - "git submodule update --init --recursive --remote"
      - "Installing/updating submodules"
