- clean: ['~', '~/.config']

- link:
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.config: config/
    ~/.Xresources: Xresources
    ~/.xinitrc: xinitrc
    ~/.i3: i3/
    ~/.tmuxinator: tmuxinator/
    ~/.xmodmaprc: xmodmaprc
