- clean: ['~']

- shell:
  - [mkdir -p ~/.bash, Creating bash sources directory]
  - [mkdir -p ~/.git, Creating git sources directory]
  - [mkdir -p ~/.local/share, Creating local/share directory]
  - [mkdir -p ~/.local/share/konsole/, Creating local/share directory]
  - [mkdir -p ~/.scripts, Creating scripts directory]
  - [mkdir -p ~/.vmail, Creating vmail config directory]
  - [mkdir -p ~/.weechat, Creating weechat config directory]
  - [touch ~/.python_history, Creating python interpreter history]

- link:
    # bashrc
    ~/.bashrc:
      path: bash/bashrc
      relink: true
      force: true
    # bash_profile
    ~/.bash_profile:
      path: bash/bash_profile
      relink: true
      force: true
    # bash
    ~/.bash/aliases:
      path: bash/aliases
      relink: true
      force: true
    ~/.bash/bashmarks:
      path: bash/scripts/bashmarks/bashmarks.sh
      relink: true
      force: true
    ~/.bash/commacd:
      path: bash/scripts/commacd/commacd.bash
      relink: true
      force: true
    ~/.bash/compilers:
      path: bash/compilers
      relink: true
      force: true
    ~/.bash/exports:
      path: bash/exports
      relink: true
      force: true
    ~/.bash/functions:
      path: bash/functions
      relink: true
      force: true
    ~/.bash/grip-chromium:
      path: bash/scripts/grip-chromium/grip-chromium.sh
      relink: true
      force: true
    ~/.bash/optprogs:
      path: bash/optprogs
      relink: true
      force: true
    ~/.bash/paths:
      path: bash/paths
      relink: true
      force: true
    ~/.bash/prompt:
      path: bash/prompt
      relink: true
      force: true
    ~/.bash/shml:
      path: bash/scripts/shml/shml.sh
      relink: true
      force: true
    ~/.bash/welcome:
      path: bash/welcome
      relink: true
      force: true

    # git
    ~/.gitconfig:
      path: git/gitconfig
      relink: true
      force: true
    ~/.git/git_commit_message_template:
      path: git/git_commit_message_template
      relink: true
      force: true
    ~/.git/ghi_token:
      path: encrypt/ghi_token
      relink: true
      force: true
    ~/.git/git-flow-completition:
      path: git/git-flow-completion/git-flow-completion.bash
      relink: true
      force: true
    ~/.git/git-hub:
      path: git/git-hub
      relink: true
      force: true

    # i3
    ~/.i3:
      path: i3
      relink: true
      force: true

    # fonts
    ~/.local/share/fonts:
      path: fonts
      relink: true
      force: true

    # icons
    ~/.local/share/icons:
      path: icons
      relink: true
      force: true

    # latex
    ~/.latexmkrc:
      path: miscellanea/latexmkrc
      relink: true
      force: true

    # X
    ~/.xinitrc:
      path: X/xinitrc
      relink: true
      force: true

    ~/.Xresources:
      path: X/Xresources
      relink: true
      force: true

    # yaourt
    ~/.yaourtrc:
      path: miscellanea/yaourtrc
      relink: true
      force: true

    # python
    ~/.gdbinit:
      path: python/gdb-dashboard/.gdbinit
      relink: true
      force: true

    ~/.pypirc:
      path: encrypt/pypirc
      relink: true
      force: true

    ~/.pythonrc:
      path: python/pythonrc
      relink: true
      force: true

    ~/.pylintrc:
      path: python/pylintrc
      relink: true
      force: true

    # scripts
    ~/.scripts/read_ini.sh:
      path: bash/scripts/bash_ini_parser/read_ini.sh 
      relink: true
      force: true
    ~/.scripts/bashsaurus:
      path: bash/scripts/bashsaurus/bashsaurus
      relink: true
      force: true
    ~/.scripts/borg-automated-backup.sh:
      path: bash/scripts/borg-automated-backup/borg-automated-backup.sh
      relink: true
      force: true
    ~/.scripts/desk:
      path: bash/scripts/desk/desk 
      relink: true
      force: true
    ~/.scripts/dpkg-install-pkgs.sh:
      path: bash/scripts/dpkg/dpkg-install-pkgs.sh
      relink: true
      force: true
    ~/.scripts/dpkg-list-pkgs.sh:
      path: bash/scripts/dpkg/dpkg-list-pkgs.sh
      relink: true
      force: true
    ~/.scripts/Ds+.sh:
      path: bash/scripts/miscellanea/Ds+.sh 
      relink: true
      force: true
    ~/.scripts/png2xvid.sh:
      path: bash/scripts/miscellanea/png2xvid.sh
      relink: true
      force: true
    ~/.scripts/proof_sheet.sh:
      path: bash/scripts/miscellanea/proof_sheet.sh
      relink: true
      force: true
    ~/.scripts/rainix:
      path: bash/scripts/miscellanea/rainix
      relink: true
      force: true
    ~/.scripts/emojify:
      path: bash/scripts/emojify/emojify
      relink: true
      force: true
    ~/.scripts/gws:
      path: bash/scripts/gws/src/gws 
      relink: true
      force: true
    ~/.scripts/remind:
      path: bash/scripts/i3-reminder/remind
      relink: true
      force: true
    ~/.scripts/alpha_image:
      path: bash/scripts/images/alpha_image
      relink: true
      force: true
    ~/.scripts/convert_image:
      path: bash/scripts/images/convert_image
      relink: true
      force: true
    ~/.scripts/crop_image:
      path: bash/scripts/images/crop_image
      relink: true
      force: true
    ~/.scripts/gray_image:
      path: bash/scripts/images/gray_image
      relink: true
      force: true
    ~/.scripts/icembackup:
      path: bash/scripts/icemcfd/icembackup
      relink: true
      force: true
    ~/.scripts/icemcfd11:
      path: bash/scripts/icemcfd/icemcfd11
      relink: true
      force: true
    ~/.scripts/icemcfd11-launch.sh:
      path: bash/scripts/icemcfd/icemcfd11-launch.sh
      relink: true
      force: true
    ~/.scripts/icemcfd11-lmgrd:
      path:  bash/scripts/icemcfd/icemcfd11-lmgrd
      relink: true
      force: true
    ~/.scripts/jpg2mjpeg:
      path: bash/scripts/miscellanea/jpg2mjpeg
      relink: true
      force: true
    ~/.scripts/overlap_image:
      path: bash/scripts/images/overlap_image
      relink: true
      force: true
    ~/.scripts/scale_image:
      path: bash/scripts/images/scale_image
      relink: true
      force: true
    ~/.scripts/trim_image:
      path: bash/scripts/images/trim_image
      relink: true
      force: true
    ~/.scripts/jpg_rename:
      path: bash/scripts/images/jpg_rename
      relink: true
      force: true
    ~/.scripts/nef_rename:
      path: bash/scripts/images/nef_rename
      relink: true
      force: true
    ~/.scripts/mountiso:
      path: bash/scripts/iso/mountiso
      relink: true
      force: true
    ~/.scripts/umountiso:
      path: bash/scripts/iso/umountiso
      relink: true
      force: true
    ~/.scripts/makeself:
      path: bash/scripts/makeself/makeself.sh
      relink: true
      force: true
    ~/.scripts/pps:
      path: bash/scripts/miscellanea/pps
      relink: true
      force: true
    ~/.scripts/texcount.pl:
      path: bash/scripts/miscellanea/texcount.pl
      relink: true
      force: true
    ~/.scripts/pacman-install-pkgs.sh:
      path: bash/scripts/pacman/pacman-install-pkgs.sh
      relink: true
      force: true
    ~/.scripts/pacman-list-pkgs.sh:
      path: bash/scripts/pacman/pacman-list-pkgs.sh
      relink: true
      force: true
    ~/.scripts/pdfA4scale:
      path: bash/scripts/pdf/pdfA4scale
      relink: true
      force: true
    ~/.scripts/spark:
      path: bash/scripts/spark/spark
      relink: true
      force: true
    ~/.scripts/sshrc:
      path: bash/scripts/sshrc/sshrc
      relink: true
      force: true
    ~/.scripts/git-remote-dropbox:
      path: python/git-remote-dropbox/git-remote-dropbox
      relink: true
      force: true
    ~/.scripts/markdown_toclify.py:
      path: python/markdown-toclify/markdown_toclify/markdown_toclify.py
      relink: true
      force: true
    ~/.scripts/pdfA4scale:
      path: bash/scripts/pdf/pdfA4scale
      relink: true
      force: true
    ~/.scripts/pdf2grey:
      path: bash/scripts/pdf/pdf2grey
      relink: true
      force: true
    ~/.scripts/pdfcompress:
      path: bash/scripts/pdf/pdfcompress
      relink: true
      force: true
    ~/.scripts/git-fire:
      path: git/git-fire/git-fire 
      relink: true
      force: true
    ~/.scripts/scholar.py:
      path: python/scholar/scholar.py
      relink: true
      force: true

    # shell
    ~/.dircolors.256dark:
      path: terminal/dircolors.256dark
      relink: true
      force: true

    ~/.inputrc:
      path: terminal/inputrc
      relink: true
      force: true

    ~/.local/share/konsole/Stefano_Zaghi.profile:
      path: terminal/konsole/Stefano_Zaghi.profile
      relink: true
      force: true

    # vim
    ~/.vim:
      path: vim/
      relink: true
      force: true

    ~/.vimrc:
      path: vim/vimrc
      relink: true
      force: true

    ~/.vmailrc:
      path: encrypt/vmailrc
      relink: true
      force: true

    # weechat
    ~/.weechat/weechat.conf:
      path: weechat/weechat.conf
      relink: true
      force: true
