- clean: ['~']

- link:
    ~/.profile: profile
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.bash_logout: bash_logout
    ~/.gitconfig: gitconfig
    ~/.vimrc: vimrc
    ~/.zshrc: zshrc
    ~/.inputrc: inputrc
    ~/.bash_aliases: bash_aliases
    ~/.functions: functions
