- clean:
  - '~'
  - '~/.config/' 

- link:
    ~/.config/colors:
        create: true
        path: colors
        force: true
    ~/.config/beets:
        create: true
        path: beets/
        force: true
    ~/.vimrc:
        path: vimrc
        force: true
    ~/.zshrc:
        path: zshrc
        force: true
    ~/.Xdefaults:
        path: Xdefaults
        force: true
    ~/.wgetrc: wgetrc
    ~/.screenrc: screenrc
    ~/.config/bspwm: bspwm/
    ~/.config/sxhkd: sxhkd/
    ~/.xinitrc: xinitrc 
    ~/.vim: 
        path: vim/
        force: true
    ~/bin: scripts/
    ~/.oh-my-zsh: oh-my-zsh/
    ~/.rtorrent.rc: rtorrent.rc

- shell: []
