- clean: ['~']

- link:
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: tmux.conf
    ~/bin:
        path: bin/
        create: true
    ~/.vimrc.local: vimrc-spf13.local
    ~/.vimrc.before.local: vimrc.before.local
    ~/.zprezto: zprezto
    ~/.zshrc: zsh/zshrc
    ~/.zlogin: zsh/zlogin
    ~/.zlogout: zsh/zlogout
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprofile: zsh/zprofile
    ~/.zshenv: zsh/zshenv

- shell:
    - ["git submodule update --init --recursive", "Installing submodules"]
    - ["mkdir -p spf13-vim/.vim 2> /dev/null", "Making spf13-vim"]
    - [sed -i -e 's/BundleInstall!/BundleInstall/g' spf13-vim/bootstrap.sh 2> /dev/null]
    - ["cd spf13-vim && APP_PATH=$(pwd) ./bootstrap.sh", "Install(Update)ing spf13-vim"]

